In [2]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
from sklearn.metrics import classification_report

In [3]:
iris = pd.read_csv("census_income_dataset.csv")
iris.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  48842.000000  4.884200e+04   48842.000000  48842.000000  48842.000000   
mean      38.643585  1.896641e+05      10.078089   1079.067626     87.502314   
std       13.710510  1.056040e+05       2.570973   7452.019058    403.004552   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.175505e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.781445e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.376420e+05      12.000000      0.000000      0.000000   
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    48842.000000  
mean        40.422382  
std         12.391444  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [ ]:
sns.pairplot(iris, hue="race")

In [ ]:
sns.lmplot(x="capital_gain", y="capital_loss", data=iris)


In [4]:
X = iris.iloc[:, [0,2,4,10,11,12]].values
y = iris['race'].values
y[:5]

array(['White', 'White', 'White', 'Black', 'Black'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
y = le.transform(y)
y[:5]

array([4, 4, 4, 2, 2])

In [6]:
iris_pred_names = le.classes_
iris_pred_names

array(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other',
       'White'], dtype=object)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
X_train[:5], X_train_std[:5]

(array([[4.30000e+01, 1.93494e+05, 1.00000e+01, 0.00000e+00, 0.00000e+00,
         4.00000e+01],
        [4.10000e+01, 5.62360e+04, 9.00000e+00, 1.50600e+03, 0.00000e+00,
         4.00000e+01],
        [3.20000e+01, 1.60362e+05, 1.00000e+01, 0.00000e+00, 0.00000e+00,
         4.00000e+01],
        [2.60000e+01, 2.66912e+05, 9.00000e+00, 0.00000e+00, 0.00000e+00,
         5.00000e+01],
        [3.80000e+01, 1.36081e+05, 1.50000e+01, 0.00000e+00, 0.00000e+00,
         6.00000e+01]]),
 array([[ 0.31725288,  0.03999094, -0.03071352, -0.14580894, -0.21550832,
         -0.03390853],
        [ 0.17127352, -1.26595797, -0.4200589 ,  0.05599427, -0.21550832,
         -0.03390853],
        [-0.48563362, -0.27524533, -0.03071352, -0.14580894, -0.21550832,
         -0.03390853],
        [-0.92357172,  0.7385306 , -0.4200589 , -0.14580894, -0.21550832,
          0.76726554],
        [-0.04769553, -0.50626826,  1.91601338, -0.14580894, -0.21550832,
          1.56843962]]))

In [9]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=100.0, random_state=1)
lr.fit(X_train_std, y_train)

LogisticRegression(C=100.0, random_state=1)

In [10]:
lr.predict_proba(X_test_std[:3, :])

array([[0.01047801, 0.02608936, 0.08887333, 0.00815221, 0.86640709],
       [0.00706446, 0.09741143, 0.04637978, 0.00121249, 0.84793184],
       [0.00349599, 0.04307428, 0.07557492, 0.00563149, 0.87222332]])

In [11]:
lr.predict_proba(X_test_std[:3, :]).sum(axis=1)

array([1., 1., 1.])

In [12]:
y_test[:3]

array([4, 4, 4])

In [13]:
lr.predict_proba(X_test_std[:3, :]).argmax(axis=1)

array([4, 4, 4], dtype=int64)

In [14]:
lr.predict(X_test_std[0, :].reshape(1, -1))

array([4])

In [15]:
X_test_std[0, :]

array([ 0.17127352, -0.35617614, -0.4200589 , -0.14580894, -0.21550832,
       -0.03390853])

In [16]:
X_test_std[0, :].reshape(1, -1)

array([[ 0.17127352, -0.35617614, -0.4200589 , -0.14580894, -0.21550832,
        -0.03390853]])

In [17]:
y_pred = lr.predict(X_test_std)

In [18]:
len(iris_pred_names)

5

In [19]:
print(classification_report(y_test, y_pred, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.00      0.00      0.00       437
             Black       0.43      0.00      0.01      1393
             Other       0.00      0.00      0.00       112
             White       0.86      1.00      0.92     12580

          accuracy                           0.86     14653
         macro avg       0.26      0.20      0.19     14653
      weighted avg       0.78      0.86      0.79     14653



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1']

In [21]:
iris_pred_names = [str(i) for i in iris_pred_names]

In [22]:
print(classification_report(y_test, y_pred, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.00      0.00      0.00       437
             Black       0.43      0.00      0.01      1393
             Other       0.00      0.00      0.00       112
             White       0.86      1.00      0.92     12580

          accuracy                           0.86     14653
         macro avg       0.26      0.20      0.19     14653
      weighted avg       0.78      0.86      0.79     14653



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Метод опорных векторов (SVC)

In [24]:
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1.0, random_state=1)
svm.fit(X_train_std, y_train)

SVC(kernel='linear', random_state=1)

In [25]:
y_pred_svm = svm.predict(X_test_std)

In [26]:
print(classification_report(y_test, y_pred_svm, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.00      0.00      0.00       437
             Black       0.00      0.00      0.00      1393
             Other       0.00      0.00      0.00       112
             White       0.86      1.00      0.92     12580

          accuracy                           0.86     14653
         macro avg       0.17      0.20      0.18     14653
      weighted avg       0.74      0.86      0.79     14653



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Нелинейная классификация

In [28]:
svm_rbf = SVC(kernel='rbf', random_state=1, gamma=0.10, C=10.0)
svm_rbf.fit(X_train_std, y_train)

SVC(C=10.0, gamma=0.1, random_state=1)

In [29]:
y_pred_svm_rbf = svm_rbf.predict(X_test_std)
print(classification_report(y_test, y_pred_svm_rbf, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.00      0.00      0.00       437
             Black       0.00      0.00      0.00      1393
             Other       0.00      0.00      0.00       112
             White       0.86      1.00      0.92     12580

          accuracy                           0.86     14653
         macro avg       0.17      0.20      0.18     14653
      weighted avg       0.74      0.86      0.79     14653



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Деревья принятия решений

In [30]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='gini', 
                              max_depth=4, 
                              random_state=1)
tree.fit(X_train_std, y_train)

DecisionTreeClassifier(max_depth=4, random_state=1)

In [31]:
y_pred_tree = tree.predict(X_test_std)
print(classification_report(y_test, y_pred_tree, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.00      0.00      0.00       437
             Black       0.00      0.00      0.00      1393
             Other       0.00      0.00      0.00       112
             White       0.86      1.00      0.92     12580

          accuracy                           0.86     14653
         macro avg       0.17      0.20      0.18     14653
      weighted avg       0.74      0.86      0.79     14653



D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Метод k-ближайших соседей

In [32]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='manhattan')
knn.fit(X_train_std, y_train)

y_pred_knn = knn.predict(X_test_std)
print(classification_report(y_test, y_pred_knn, target_names=iris_pred_names))

                    precision    recall  f1-score   support

Amer-Indian-Eskimo       0.00      0.00      0.00       131
Asian-Pac-Islander       0.16      0.03      0.05       437
             Black       0.19      0.06      0.09      1393
             Other       0.00      0.00      0.00       112
             White       0.86      0.97      0.91     12580

          accuracy                           0.84     14653
         macro avg       0.24      0.21      0.21     14653
      weighted avg       0.76      0.84      0.79     14653

